// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9QEgsfnM3YP4Aisgygy3ZVGthQMpTxmk',
    appId: '1:726733541954:web:303d93ef1e8618c2c593db',
    messagingSenderId: '726733541954',
    projectId: 'online-shopping-bce1e',
    authDomain: 'online-shopping-bce1e.firebaseapp.com',
    storageBucket: 'online-shopping-bce1e.appspot.com',
    measurementId: 'G-XPF9JLCEZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpzxuTctVKPznMI3xLKJSTknCInRZlThE',
    appId: '1:726733541954:android:3f43e9fa2a2fc872c593db',
    messagingSenderId: '726733541954',
    projectId: 'online-shopping-bce1e',
    storageBucket: 'online-shopping-bce1e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVCdzDLllCHYXRfrc_gcQnoP8-3t_xApw',
    appId: '1:726733541954:ios:20949c948291cea1c593db',
    messagingSenderId: '726733541954',
    projectId: 'online-shopping-bce1e',
    storageBucket: 'online-shopping-bce1e.appspot.com',
    iosBundleId: 'com.example.onlineShopping',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVCdzDLllCHYXRfrc_gcQnoP8-3t_xApw',
    appId: '1:726733541954:ios:9459a223125f380fc593db',
    messagingSenderId: '726733541954',
    projectId: 'online-shopping-bce1e',
    storageBucket: 'online-shopping-bce1e.appspot.com',
    iosBundleId: 'com.example.onlineShopping.RunnerTests',
  );
}
